FROM alpine AS add
LABEL DL=3020
ADD https://dl.winehq.org/wine/source/1.9/wine-1.9.19.tar.bz2 /
RUN tar -xf wine-1.9.19.tar.bz2 && rm wine-1.9.19.tar.bz2

FROM alpine AS wget
LABEL DL=3020
RUN wget https://dl.winehq.org/wine/source/1.9/wine-1.9.19.tar.bz2 \
    && tar -xf wine-1.9.19.tar.bz2 \
    && rm wine-1.9.19.tar.bz2
